// styles.js
const styles = {
    container: {
      fontFamily: "'Inter', sans-serif",
      backgroundColor: 'transparent',
      color: '#fff',
      scrollBehavior: 'smooth',
      overflowX: 'hidden',
      overflowY: 'auto',
    },
    section: {
      padding: '80px 20px',
      minHeight: '100vh',
      backgroundColor: '#000',
      color: '#fff',
    },
    anchorHeader: {
      fontSize: '2.5rem',
      marginBottom: '2rem',
      color: '#fff',
      textAlign: 'center',
    },
    nav: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      padding: '20px',
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      display: 'flex',
      justifyContent: 'center',
      zIndex: 100,
    },
    navList: {
      position: 'relative',
      display: 'flex',
      listStyle: 'none',
      gap: '30px',
      padding: 0,
      margin: 0,
    },
    navLink: {
      color: 'white',
      textDecoration: 'none',
      fontSize: '18px',
      cursor: 'pointer',
      padding: '8px 12px',
      position: 'relative',
      transition: 'color 0.3s ease',
    },
    heroContainer: {
      position: 'relative',
      width: '100%',
      height: '100vh',
      overflow: 'hidden',
    },
    videoBackground: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: -1,
      pointerEvents: 'none',
    },
    heroContent: {
      position: 'relative',
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'flex-start',
      padding: '0 40px',
      zIndex: 1,
    },
    heroText: {
      fontSize: '3.5rem',
      fontWeight: 'bold',
      color: '#fff',
      maxWidth: '800px',
      textAlign: 'left',
      lineHeight: '1.3',
    },
    masonryGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gridAutoRows: '200px',
      gap: '20px',
      justifyContent: 'center',
      alignItems: 'center',
      maxWidth: '1200px',
      margin: '0 auto 40px auto',
    },
    masonryItem: {
      borderRadius: '12px',
      overflow: 'hidden',
      boxShadow: '0 4px 14px rgba(0, 0, 0, 0.2)',
      transition: 'transform 0.3s ease, box-shadow 0.3s ease',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
    },
    masonryItemHover: {
      transform: 'scale(1.03)',
      boxShadow: '0 6px 20px rgba(0, 0, 0, 0.3)',
    },
    backButton: {
      position: 'absolute',
      top: '20px',
      left: '20px',
      background: 'none',
      border: 'none',
      color: '#fff',
      fontSize: '1.5rem',
      cursor: 'pointer',
      zIndex: 10,
    },
    loader: {
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100vw',
      height: '100vh',
      backgroundColor: '#000',
      color: '#fff',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 2000,
      transition: 'opacity 1s ease-in-out',
    },
    loaderText: {
      fontSize: '3rem',
      animation: 'fadeSlide 2s ease-in-out forwards',
      color: '#fff',
    },
    projectGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
      gap: '30px',
      marginTop: '40px',
      padding: '0 20px 60px 20px',
      backgroundColor: '#000',
      color: '#fff',
    },
    projectCard: {
      backgroundColor: '#111',
      padding: '20px',
      borderRadius: '16px',
      textAlign: 'center',
      transition: 'transform 0.5s ease, opacity 0.5s ease',
      cursor: 'pointer',
      boxShadow: '0 4px 14px rgba(255,255,255,0.05)',
    },
    moreProjectsButton: {
      padding: '12px 24px',
      borderRadius: '30px',
      textDecoration: 'none',
      fontWeight: 'bold',
      fontSize: '16px',
      display: 'inline-block',
      color: '#fff',
      background: '#222',
      border: '1px solid #444',
      transition: 'all 0.4s ease-in-out',
      margin: '40px auto 0 auto',
      cursor: 'pointer',
    },
  };
  
  export default styles;
  